= 2. Interacting with Your LLM using Python

In this short module, our primary goal is to verify that we can successfully run simple Python applications that communicate with our running Large Language Model (LLM). Recall from Module 1 that we are using `ollama` (which internally uses `llamacpp`) as our LLM runtime.

This module also marks a transition: from this point forward, all technical instructions, code examples, and detailed explanations for the lab exercises will be presented within Jupyter Notebooks.

Take a few moments to familiarize yourself with the JupyterLab interface. JupyterLab is a web-based interactive development environment. We'll be using Jupyter Notebooks (`.ipynb` files) within it. Notebooks are documents that can contain both runnable Python code (in "code cells") and explanatory text, images, and links (in "markdown cells"). This format is excellent for learning and experimentation.

Please switch your focus to the "JupyterLab" tab, located to the right in your lab interface tab bar. You can adjust the width of this panel by dragging the divider if you need more space. Once in the JupyterLab tab, locate and open the notebook for this module: `02-talk-to-your-llm.ipynb`. All further instructions for this section will be found inside that notebook.

== JupyterLab and Jupyter Notebooks 

[NOTE]
====
This lab runs in JupyterLab, an interactive development environment you'll access directly through your web browser. Think of JupyterLab as a workbench that's excellent for hands-on experimentation, which is especially useful in AI development.

Within JupyterLab, we'll be using Jupyter Notebooks. A Notebook is like an interactive document where you can:

* Write and execute Python code in small, manageable cells.
* Instantly see the output from your code.
* Easily modify code and vars and re-execute 
* Combine code with explanatory text (like this!), images, and charts, all in one place.
This combination makes Notebooks ideal for learning new concepts and testing ideas step-by-step.

.Quick interactive introduction to using and customizing Jupyter Lab (recommended)
++++
<iframe 
  src="https://demo.arcade.software/eF1CtDuuD4hKWspBmiYR?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true"
  width="100%" 
  height="600px" 
  frameborder="0" 
  allowfullscreen
  webkitallowfullscreen
  mozallowfullscreen
  allow="clipboard-write"
  muted>
</iframe>
++++

====

